#!/bin/bash
cd /app/bundle

# Set a delay to wait to start meteor container
if [[ $DELAY ]]; then
  echo "Delaying startup for $DELAY seconds"
  sleep $DELAY
fi

export PORT=${PORT:-3000} MONGO_URL=mongodb://127.0.0.1:27017 ROOT_URL=http://127.0.0.1
echo "=> Starting meteor app on port:$PORT"
exec /sbin/setuser abc node main.js



