#!/bin/bash
cd /app/bundle

# Set a delay to wait to start meteor container
if [[ $DELAY ]]; then
  echo "Delaying startup for $DELAY seconds"
  sleep $DELAY
fi

export PORT=${PORT:-3000} MONGO_URL=mongodb://localhost:27017/db
echo "=> Starting meteor app on port:$PORT"
exec /sbin/setuser abc node main.js

